[tox]
envlist = py{37, 38, 39, 310, 311, 312}
requires = virtualenv>=20.0

[ruff]
profile = black

[testenv]
description = code format check, CI, CD
setenv =
    PKG_MODULE_PATHS = unittests src
deps =
    pytest==8.1.0
    ruff==0.5.7
commands =
    ruff check {env:PKG_MODULE_PATHS}
    pytest unittests
