[tox]
envlist = py{38, 39, 310, 311, 312}
requires = virtualenv>=20.0

[pytest]
filterwarnings = ignore::Warning

[testenv]
description = run linters
setenv =
    PKG_MODULE_PATHS = unittests src
deps =
    ruff==0.5
commands =
    ruff check --output-format=pylint {env:PKG_MODULE_PATHS}
